### ISSUE TITLE
关于process_kg.ipynb

### ISSUE THREAD

**Issue by applelalala** [JieZheng-ShanghaiTech/NSF4SL#3]
您好！我想再冒昧的请教一下，运行process_kg.ipynb文件，出现Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\envs\pytorch\Scripts\dglke_train.exe\__main__.py", line 7, in <module>
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\dglke\train.py", line 86, in main
    args.has_edge_importance)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\dglke\dataloader\KGDataset.py", line 647, in get_dataset
    assert data_name != 'FB15k', 'You should provide the dataset name for raw_udd format.'
AssertionError: You should provide the dataset name for raw_udd format.    想问下您出现过这类情况吗？

**Comment by shikew** [comment]
您好，
好像没有。可以试试加一个```--dataset your_dataset_name```的超参。
